# Test suite must pass on GitHub Actions before merging into `master`.
status = [
    "CI%",
]

# Do not allow pull requests with these labels to be merged.
block_labels = [
    "status: blocked",
    "status: discussing",
    "status: in progress",
    "status: needs triage"
]

# This feature is rarely useful and more often problematic, so we turn it off.
delete_merged_branches = false

# Increase timeout to 5 hours as the default timeout is too short for our build
timeout_sec = 18000

[committer]
name = "amethyst-bot"
email = "5838512+CleanCut@users.noreply.github.com"